### ISSUE TITLE
USB power warning despite having USB_MAX_CURRENT_ENABLE=1 set

### ISSUE THREAD

**Issue by andrum993** [raspberrypi-ui/wf-panel-pi#20]
Not sure which component this is coming from, but I'm seeing this warning when I log into the desktop on a Pi 5:

`This power supply is not capable of supplying 5V at 5A`
`Power to peripherals will be restricted`

despite having USB_MAX_CURRENT_ENABLE=1 set in config.txt, and having rebooted since I set it.

**Comment by spl237** [comment]
That's by design. The power supply *is* incapable of supplying 5V at 5A, so the warning persists even if the config.txt flag is set - all that does is to allow the system to get past the bootloader test for a suitable PSU on a PI 5.

If you buy the approved Raspberry Pi power supply, the message will then go away - consider it marketing... ;)

**Comment by Botspot** [comment]
Suppose that a university or school buys a large quantity of Pi5 boards and integrates them into monitors. Namely, each Pi5 is powered by 5V 5A supplied straight to the GPIO header in this semi-embedded application.
The message is confusing and annoying users on every boot. Is there a way to disable the message?

**Comment by spl237** [comment]
> Is there a way to disable the message?

Remove the Power plugin from the panel.
