### ISSUE TITLE
Deletes .asoundrc without my permission

### ISSUE THREAD

**Issue by tomhaines** [raspberrypi-ui/wf-panel-pi#9]
This deletes my .asoundrc file on reboot whether I want it to or not. 

https://github.com/raspberrypi-ui/wf-panel-pi/blob/23e526d8b66b5a787546c5995b84c7865a35cf7a/src/panel/widgets/volumepulse/volumepulse.c#L443

An rm -f command should not be permitted against a user's files.

**Comment by spl237** [comment]
You shouldn't be using an .asoundrc file. It will clash with the audio control by Pipewire, which is run by default on the desktop.

If you really want to use plain ALSA to control audio - and it is not recommended, because Pipewire is far more flexible and configurable; the only real reason to use plain ALSA is because it has slightly better latency - then just right-click the taskbar, choose Add/Remove Plugins, and remove the Volume plugin, which is a Pipewire controller and contains the code which deletes .asoundrc.

Bear in mind that if you do this, you will need to use some other mechanism to control volume, input/output device selection etc. It is much easier to just not try to control ALSA directly, and to stop trying to use .asoundrc, but it is up to you.

**Comment by tomhaines** [comment]
Whether I can disable it, or whether or not I have a valid use case for configuring ALSA and not Pipewire is beside the point. 

Your application needs to respect the users configuration choices on their machine, and not work to actively corrupt it.

Even if there is a workaround for this, It is terrible practice to delete user files from within a user's home directory without documentation or consent. 

This needs to be changed.

**Comment by spl237** [comment]
This has been the default behaviour of the Pipewire (and before it the Pulseaudio) controller for several years now. Removing that file is necessary to make said controllers work correctly.

You are in a small minority of people who wish to use an outdated configuration method, and not deleting the file will cause problems for the majority of people who use the current method. 

I have told you how to address the problem on your system. The code will not be changed.
